- name: setup backend server
  hosts: backend
  become: yes
  tasks:
  - name: disable nodejs commands
    ansible.builtin.command: dnf module disable nodejs -y
  - name: enable nodejs commands
    ansible.builtin.command: dnf module enable nodejs:20 -y
  - name: install nodejs
    ansible.builtin.package:
      name: nodejs
      state: present
  - name: add expense user
    ansible.builtin.user:
      name: expense
      comment: add expense system user
      system: true

