- name: setup mysql server
  hosts: mysql
  become: yes
  tasks:
  - name: install nginx
    ansible.builtin.package:
      name: mysql-server
      state: present

  - name: start and enable mysql
    ansible.builtin.systemd_service:
      name: mysqld
      state: started
      enabled: true

  - name: setup root password
    ansible.builtin.command: mysql_secure_installation --set-root-pass ExpenseApp@1

  - name: creating app directory
    ansible.builtin.file:
      state: directory
      path: /app

  - name: Download the expense application
    ansible.builtin.get_url:
      url: https://expense-joindevops.s3.us-east-1.amazonaws.com/expense-backend-v2.zip
      dest: /tmp/backend.zip

  - name: Unarchive a file that is already on the remote machine
    ansible.builtin.unarchive:
      src: /tmp/backend.zip
      dest: /app
      remote_src: yes


